import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>R-MEN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-yellow-100 h-screen">
        <div className="bg-r-men-img w-full object-contain bg-contain xl:bg-cover pb-14">
          <div className="md:w-1/3 z-10 h-64">
            <div className="grid grid-cols-3 place-content-center h-16 py-5">
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Login
                </a>
              </Link>
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Sign Up
                </a>
              </Link>
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Guest
                </a>
              </Link>
            </div>

            <div className="pt-2">
              <p className="text-5xl text-red-400 font-serif text-center">
                R-MEN
              </p>
              <p className="text-2xl font-bold text-black-400 font-serif text-center py-4">
                find your best r-men
              </p>
            </div>
          </div>
        </div>

        <div className="container bg-gray-400 mx-auto py-10">
          <h1 className="mx-auto text-4xl text-center font-serif ">
            おすすめから探す
          </h1>
          <div className="grid grid-cols-2 place-content-center h-16 py-5 my-5">
            <p className="text-center mb-5">各エリアランキングTOP20</p>
            <p className="text-center mb-5">ユーザーおすすめ一覧</p>
            <p className="text-center">SNSで話題のラーメン</p>
            <p className="text-center">運営おすすめ</p>
          </div>
        </div>
        <div className="container bg-gray-400 mx-auto pb-10">
          <h1 className="mx-auto text-4xl text-center font-serif">
            カテゴリから探す
          </h1>
        </div>
        <div className="container bg-gray-400 mx-auto pb-10">
          <h1 className="mx-auto text-4xl text-center font-serif">
            エリアから探す
          </h1>
        </div>
      </main>

      <footer className="h-16">
        <div className="float-left w-1/2 text-2xl pl-12 text-red-400 h-full flex content-center flex-wrap">
          <p className="text-left">R-MEN</p>
        </div>
        <div className="float-right  w-1/2 grid md:grid-cols-4 grid-cols-2 h-full text-sm  flex content-center flex-wrap">
          <p className="text-center text-gray-500">About</p>
          <p className="text-center text-gray-500">利用規約</p>
          <p className="text-center text-gray-500">プライバシーポリシー</p>
          <p className="text-center text-gray-500">サイトマップ</p>
        </div>
      </footer>
    </div>
  );
}
