import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className=" bg-r-men-img w-full object-contain bg-contain xl:bg-cover pb-14">
          <div className="md:w-1/3 z-10 h-64">
            <div className="grid grid-cols-3 place-content-center h-16 py-5">
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Login
                </a>
              </Link>
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Sign Up
                </a>
              </Link>
              <Link href="/">
                <a className="text-gray-700 text-center px-4 py-2 m-2 font-medium">
                  Guest
                </a>
              </Link>
            </div>

            <div className="pt-2">
              <p className="text-5xl text-red-400 font-serif text-center">
                R-MEN
              </p>
              <p className="text-2xl font-bold text-black-400 font-serif text-center py-4">
                find your best r-men
              </p>
            </div>
          </div>
        </div>

        <div className="container bg-gray-400 mx-auto mt-10">
          <h1 className="mx-auto text-4xl text-center font-serif">
            おすすめから探す
          </h1>
        </div>
        <div className="container bg-gray-400 mx-auto mt-10">
          <h1 className="mx-auto text-4xl text-center font-serif">
            カテゴリから探す
          </h1>
        </div>
        <div className="container bg-gray-400 mx-auto mt-10">
          <h1 className="mx-auto text-4xl text-center font-serif">
            エリアから探す
          </h1>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
